[package]
name = "panic"
authors = ["The Project Mu Rust Developers"]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "panic"
crate-type = ["rlib", "staticlib"]
