[package]
name = "panic"
authors = ["The Project Mu Rust Developers"]
version = "0.1.0"
edition = "2018"

[lib]
name = "panic"
crate-type = ["rlib", "staticlib"]

[dependencies]
core-con-out = { path = "../core_con_out" }
